formatter: "md table"
header-from: main.tf

recursive:
  # Enable this if your module has submodules
  enabled: false

content: |-
  {{ include "docs/10-header.md" }}

  {{ include "docs/20-badges.md" }}

  {{ .Header }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  ## Resources
  {{ range .Module.Resources }}
  - {{ .GetMode }}.{{ .Spec }} ({{ .Position.Filename }}#{{ .Position.Line }})
  {{- end }}

  # Examples
    ### ALB Logs
    ```hcl
    {{ include "examples/alb-access-logs/main.tf" }}
    ```

    ### Cloudfront Logs
    ```hcl
    {{ include "examples/cloudfront-access-logs/main.tf" }}
    ```

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  lockfile: false
